[package]
name = "compress-rs"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
lazy_static = "1.5"
paste = "1.0.15"
macros = { path = "../macros" }

[build-dependencies]
cxx-build = "1.0"