[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
cxx = "1.0"
cxxbridge-macro = "1.0"
paste = "1.0.15"
syn = { version = "2", features = ["full", "printing"]}
quote = "1.0.39"